### ISSUE TITLE
motor.on_for_seconds() not working : infinite block

### ISSUE THREAD

**Issue by loikun** [QuirkyCort/ev3dev-sim#10]
A call to on_for_seconds() will block indefinitely.
In this small example, the robot motion will never end.
```
from ev3dev2.motor import LargeMotor, OUTPUT_C

lm = LargeMotor(OUTPUT_C)

lm.on_for_seconds(speed=50, seconds=4)
lm.off()
```
I will try soon to solve the issue with the missed timeout of this function.

**Comment by QuirkyCort** [comment]
Thanks for letting me know. It doesn't actually blocks forever, just for a very long time. I was mistakenly using milliseconds instead of seconds, so the duration got multiplied by 1000. Fixed.
