### ISSUE TITLE
Running Offline

### ISSUE THREAD

**Issue by birrelln** [QuirkyCort/ev3dev-sim#2]
I think offline is in your TODO list, but it doesn't seem to work right now.  When I try and run code, it gives the following error:

ImportError: No module named ev3dev2 on line 5

Any workaround at this time?

**Comment by birrelln** [comment]
To add some info, I was initially just extracting the files and trying to run it from a directory on the hard drive.  In addition to the import error, the about and guide windows were empty.

Using IIS, I have now put the contents of everything into the wwwroot folder and am running it from a local web server.  The about and guide windows now contain the correct things, but the following comes up when attempting to run code:

SyntaxError: bad input on line 1

**Comment by QuirkyCort** [comment]
Hi Birrelln. I just tried it out myself. Seems that for security reasons, web browsers (...I've tried Chrome and Firefox) blocks certain types of requests when running the files locally. Unfortunately, I don't see any way to workaround this other than to run a local webserver.

As for the "SyntaxError: bad input on line 1", that's generated by the Skulpt Python engine. It thinks that there's something wrong with the Python code. Can you share what you have inside the Python textbox when you encounter this error? Did you encounter this error when running it from https://www.aposteriori.com.sg/Ev3devSim/index.html ?

**Comment by birrelln** [comment]
Hi Cort,

Everything works well form your website - no errors that I have found yet.

When I run it on a local server is where the trouble begins.  The code inside the Python textbox is the default code that you include so the first line is a comment. 

Playing around with it, I can write and run regular Python scripts.  I think the problem is in attempting to import the ev3dev2 files.  If I wipe out the import statements on the default script, the error becomes:

NameError: name 'MoveSteering' is not defined on line 6

This makes sense as the import is no longer there.

**Comment by QuirkyCort** [comment]
Hm... If it runs fine from my website, then there's probably something wrong with the way IIS is serving up the files. I'm guessing that IIS is trying to interpret the Python scripts rather than just serving them up. If you don't mind, let's do a little sleuthing.

First, use open a new tab and open the developer console (...F12 for Chrome and Firefox). Switch to the network tab.

Next, load the ev3dev site. The network tab should show a bunch of files loading.

Click "Run" to start the simulation. This should cause 5 more files to be loaded; __init__.py (...appears twice), motor.py, ev3dev2_glue.js, and lego.py. The problem should be with one of the Python files.

Click on motor.py and it should open up a new panel with tabs such as "Headers", "Preview", etc. Select "Response" and take a look at what you got. If it doesn't look the same as the motor.py file from the package, then IIS is probably interpreting it. You can either try to configure IIS to serve it up as a regular file, or switch to a different webserver. If you have Python3 installed, changing to the ev3devSim directory and running "python3 -m http.server 1337" should be all you need to get the site running on http://localhost:1337.

**Comment by birrelln** [comment]
Developer console is handy!

__init__.py gives HTTP Error 404.3 - Not Found

Now, when I look in the motor directory, that init.py is 0 kb and empty.

The one in the sensor directory is 1kb and has:

INPUT_1 = 'in1'
INPUT_2 = 'in2'
INPUT_3 = 'in3'
INPUT_4 = 'in4'

Should there be any entries in the motor __init__.py?

The python server method isn't working for me, but I will play around with it some more.

Here is the full error for __init__.py.  I will have to look into some its suggestions as it looks like a server issue.

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

Most likely causes:
It is possible that a handler mapping is missing. By default, the static file handler processes all content.
The feature you are trying to use may not be installed.
The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.)
If ASP.NET is not installed.

Things you can try:
In system.webServer/handlers:
Ensure that the expected handler for the current page is mapped.
Pay extra attention to preconditions (for example, runtimeVersion, pipelineMode, bitness) and compare them to the settings for your application pool.
Pay extra attention to typographical errors in the expected handler line.
Please verify that the feature you are trying to use is installed.
Verify that the MIME map is enabled or add the MIME map for the Web site using the command-line tool appcmd.exe.
To set a MIME type, use the following syntax: %SystemRoot%\windows\system32\inetsrv\appcmd set config /section:staticContent /+[fileExtension='string',mimeType='string']
The variable fileExtension string is the file name extension and the variable mimeType string is the file type description.
For example, to add a MIME map for a file which has the extension ".xyz": appcmd set config /section:staticContent /+[fileExtension='.xyz',mimeType='text/plain']
Warning: Ensure that this MIME mapping is needed for your Web server before adding it to the list. Configuration files such as .CONFIG or dynamic scripting pages such as .ASP or .ASPX, should not be downloaded directly and should always be processed through a handler. Other files such as database files or those used to store configuration, like .XML or .MDF, are sometimes used to store configuration information. Determine if clients can download these file types before enabling them.
Install ASP.NET.
Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here.

More Information:
This error occurs when the file extension of the requested URL is for a MIME type that is not configured on the server. You can add a MIME type for the file extension for files that are not dynamic scripting pages, database, or configuration files. Process those file types using a handler. You should not allows direct downloads of dynamic scripting pages, database or configuration files.


Module | StaticFileModule
-- | --
ExecuteRequestHandler
StaticFile
0x80070032

**Comment by QuirkyCort** [comment]
The empty \_\_init\_\_.py is normal. It's just there to let Python know that the directory contains a module and need not contain anything.

As suspected, IIS is trying to interpret the Python files. As the error messages suggests, you'll need to add a mime map (...don't add a handler). Unfortunately, I don't use IIS and can't help you with that.

If the Python server runs, but you can't connect to it, try using http://127.0.0.1:1337 instead. Heard that localhost don't always work on windows.

**Comment by birrelln** [comment]
Cort, you are fantastic!

It absolutely was an IIS issue.  **For those playing at home, the solution was as simple as adding a MIME type for .py and setting it as text/plain.**

The python server did not work out, so I may try writing a little webserver script for that for students to use on thier personal devices but your simulator will hopefully just live on a school division server.  I'm working on making an online introductory 3D CAD \ Coding \ Robotics course for my school division and would like to use your virtual robot for part of it.  

Thanks for the assistance in getting it running.

**Comment by QuirkyCort** [comment]
Glad that it's working for you. I'll close this issue, but if you manage to get the Python server working, let me know how and I'll add the instructions to the README. I don't use windows myself, so it's hard for me to figure out suitable instructions for windows users.

If you need teaching materials for robotics and coding, you can take a look at my site; https://aposteriori.com.sg. We teach STEM and robotics in Singapore and share everything we prepare.

**Comment by birrelln** [comment]
Well, I don't know why the Python server was not working before, but it is working beautifully now.  I ended up creating a .bat file to run from the ev3devsim directory that has the following line:

python -m http.server 1337

Change the 1337 to whatever port you want and it should work as long as Python is in the path.  Then you can access it from:

http://localhost:1337/

Closing the window Python opens will stop the server.
