### ISSUE TITLE
Click to Measure -> on_for_rotations() and distance discrepancy

### ISSUE THREAD

**Issue by birrelln** [QuirkyCort/ev3dev-sim#4]
Hi Cort,

I am having an issue with the robot moving expected distances.

Here is the simplest program:

from ev3dev2.motor import MoveSteering, OUTPUT_B, OUTPUT_C

steering_drive = MoveSteering(OUTPUT_B, OUTPUT_C)

steering_drive.on_for_rotations(0, 50, 1)

With the default robot configuration (56 mm diameter wheels) I would expect the robot to move 175.84 mm in one rotation.  However, it moves about double according to the click and measure line.  Am I going wrong somewhere?

Edit: Same issue with on_for_degrees() as well as if using TankSteering

Edit Edit:  Changing in ev3DevSim line 435ish:
wheel.pos += dist;

to

wheel.pos += dist * 2;

Makes it work like I think it should.  I don't know why though...

**Comment by QuirkyCort** [comment]
Thanks for the bug report. What's happening is that I was incorrectly adding the distance travelled (...in mm) to the wheel position (...which should be in degrees).

As it happens, for a 56mm wheel, the distance travelled is close to half the degrees rotated, so your fix of multiplying the distance by 2 somewhat works, but it'll be incorrect if a different wheel size is used. I've fixed it properly, and both the github version and the one on aposteriori.com.sg should be correct now.

**Comment by birrelln** [comment]
Excellent!  You are fast.

I have added a "Reset" button that stops and moves the animation back to the map's specified xPos, yPos, and angle - it is pretty useful!

I am working on a "Reset and Run" button that would stop the sim, reset the bot back to the initial xPos, yPos, and angle, and start running the script again.  Having trouble getting the script to run again though.  I may have to figure out how github pull requests work...
