### ISSUE TITLE
Support for sound / speak

### ISSUE THREAD

**Issue by psychemedia** [QuirkyCort/ev3dev-sim#7]
I notice in the `ev3dev` docs an example of getting the robot to speak using simple text to speech:

```
from ev3dev2.sound import Sound

sound = Sound()
sound.speak('Welcome to the E V 3 dev project!')
```

Could this be implemented using the browser

In a Jupyter notebook, this would be something like:

```
from IPython.display import Javascript

txt = 'hello'
Javascript(f'speechSynthesis.speak(new SpeechSynthesisUtterance("{txt}"))')
```

**Comment by psychemedia** [comment]
A simple speak function for skulpt:

```javascript

function say (obj) {
    speechSynthesis.speak(new SpeechSynthesisUtterance(obj.$jsstr()))
  }
  
var $builtinmodule = function(name)
{
    var mod = {};

    mod.say = new Sk.builtin.func(function(obj){
        say(obj);
        return new Sk.builtin.none;
    })

    return mod;
}
```

Python usage is:

```python
import playsound
playsound.say('hello world')
```

**Comment by QuirkyCort** [comment]
Done. Using the ev3dev2 API. Only speech is supported, play_tone, beep, etc doesn't work.

For simplicity, I'm using the experimental speechSynthesis API as you have suggested, though it may be more consistent to use espeak like an actual EV3.
